### PR TITLE
ICONS: Update icon for myst3-myst3 (better crop)

### PR DESCRIPTION
**Pull request by beresk137**
Made the icon more similar to Riven's one in terms of composition. It also resembles the original cover art better now.

### CODE REVIEW

**Comment by tag2015** [comment]
Hmm, not too sure about this change. The current one is already good IMHO, and has better lettering

**Comment by Thunderforge** [comment]
I'm not as fond of this change with the thin picture. Also, it kind of looks like, well, 🍆.

If you want a picture that isn't overlapping with the photo, I'd recommend just the house without the tusk.

**Comment by GandalfTheWhite80** [comment]
I was also working on a myse3 icon - give a few min. Maybe we could choose the "better fitting" one :-)

**Comment by GandalfTheWhite80** [comment]
ah sry for the confusion - updated the myst3 olnyl with a higher res version

https://github.com/scummvm/scummvm-icons/commit/9123ddf6c62e3b167c8f5ff9e8bf61f9d01d1ffd

**Comment by GandalfTheWhite80** [comment]
@Thunderforge  I like your idea about removing the tusk but i'm not shure about the right place of "croping"... made a (in my opintion) slightly better readable version of this request (version 3)

myst3-myst3-v3-ovn

**Comment by GandalfTheWhite80** [comment]
Version 4...
myst3-myst3-v4

**Comment by beresk137** [comment]
@tag2015 thank you for your notes! I do see the difference in lettering, and I do agree that my variant is a bit more blurry (my mistake).

@Thunderforge well, that was a fair point of you as well! And you were correct that my primary intention was to separate the logo and the image, thank you.

@GandalfTheWhite80 several options, very nice, — and thank you as well! I personally like the 4th one the most. The only suggestion I would offer is not to crop the lower (albeit thin) part of the tusk: it could give a visual context and remove the illusion that the house is floating in the air.

**Comment by GandalfTheWhite80** [comment]
myst3-myst3-v4a

**Comment by beresk137** [comment]
@GandalfTheWhite80 I believe that your version is the definite one to propose now. Thank you for your work!

**Comment by GandalfTheWhite80** [comment]
Ok - lets drop this pr. I would to mention you as (co)author for the new myst3 icon.  Ok?

**Comment by GandalfTheWhite80** [comment]
Done: https://github.com/scummvm/scummvm-icons/commit/5e083d5bf7c4a46d5119ea86413602a6acf8de98

**Comment by beresk137** [comment]
I appreciate that!
But I believe I have not contributed enough to this exact icon to count myself as a coauthor. The stage is all yours!

**Comment by Thunderforge** [comment]
I'm also in favor of the version from @GandalfTheWhite80. Glad we could reach an agreement on this!

**Pull request closed without merging**
