### PR TITLE
GUI: Add missing flags + rework

### PR DESCRIPTION
**Pull request by tag2015**
GUI: Add missing flags + rework

Added missing flags
Resized to keep a coherent look
Replaced complex flags with simpler versions

### CODE REVIEW

**Comment by sev-** [comment]
Arabic flag is something unusual. "Flag of the Arab revolt of 1916"? Doesn't seem right to me.

Perhaps this one is better suited? https://www.metroflags.com/language-flags/arabic-lang-flag/

**Comment by sev-** [comment]
Serbian flag is very weird, e.g. you striped corona and left only coat of arms. I did not hear about that flag variant and Wikipedia does not enlist it: https://en.wikipedia.org/wiki/List_of_Serbian_flags

**Comment by sev-** [comment]
The same thing is with the Spanish flag. I think we need to be careful when striping down crowns ;)

**Comment by sev-** [comment]
Also, I would be much careful with removing Allahu Akbar from the Iranian flag...

**Comment by tag2015** [comment]
Regarding the arabian flag, I picked that one because it has no writings and many national flags are derived from it ... but still, i'm no expert and since we are talking about language instead of territory, the one you mentioned is fine i guess.
The serbian one is a rework, as there's no way to remove the eagle.
For spain we could also remove the badge entirely, the "clear" flag is well-known.
However, my idea was simply to reduce the complexity of flags, mostly considering that the features are so small they are impossible to see in the gui.  If the changes may offend someone (to be honest, seems unlikely to me...) I'll be happy to revert them as needed.

**Comment by trembyle** [comment]
> Regarding the arabian flag, I picked that one because it has no writings and many national flags are derived from it ... but still, i'm no expert and since we are talking about language instead of territory, the one you mentioned is fine i guess. 

I have a plan to review the games with an Arab community organization in my neighborhood, as I believe many of these are specifically Masri (Egyptian) dialect, and so can be assigned a country flag. In the meantime, I would suggest that we use the flag for the Arab League.
https://en.wikipedia.org/wiki/Arab_League#/media/File:Flag_of_the_Arab_League.svg

**Comment by trembyle** [comment]
> However, my idea was simply to reduce the complexity of flags, mostly considering that the features are so small they are impossible to see in the gui. If the changes may offend someone (to be honest, seems unlikely to me...) I'll be happy to revert them as needed.

I see where you're coming from, but I feel like it's best that we use the official state (or regional) flag without modifications. Any changes could be seen as taking a political position, which is something we want to avoid.

**Comment by trembyle** [comment]
The flag for NL_BEL is specifically for the Flemish region, which has its own accepted subnational flag.
https://en.wikipedia.org/wiki/Flanders#/media/File:Flag_of_Flanders.svg

**Comment by trembyle** [comment]
I think the Brazilian flag too may be oversimplified. Is this your own interpretation, or have you seen an official simplified flag without the southern hemisphere stars?

**Comment by trembyle** [comment]
As for the `zh` code, I think we should be very careful about how to handle that one. Maybe we should review the games that still require ZH_ANY since the specific Taiwan / China regions have been in use. I'm assuming that those can default to the release country.

Even Return to Zork (which uses only Chinese dubbing, no text) does have a Traditional Chinese title on the box. It was sold in Hong Kong and Taiwan and in only limited quantities in the mainland.

**Comment by tag2015** [comment]
The matter here is that the current svg renderer has problems drawing complex flags. The whole idea was to (temporarily) provide simplified flags that would draw properly and be clearly distinguishable. Of course, the best solution would be to have the unmodified flags.
However if you think there are so many implications related to this, maybe it would be better to remove the "problematic" flags completely until the svg renderer is improved or use bitmaps instead of svg for now.

**Comment by tag2015** [comment]
Finally updated this PR, removed "reworked" flags and added normal .pngs
Should be used with https://github.com/scummvm/scummvm/pull/4613

**Comment by sev-** [comment]
Thanks!

**Pull request merged**
