### PR TITLE
ICONS: updated 3 icons by Telev78 #scummvm103

### LINKED ISSUE #103: 3 updated icons (scumm-monkey / scumm-monkey2 / scumm-indy3)
update of these 3 icons 

- scumm-monkey.png
- scumm-monkey2.png
- scumm-indy3.png

[icons.zip](https://github.com/scummvm/scummvm-icons/files/7889011/icons.zip)

### PR DESCRIPTION
**Pull request by GandalfTheWhite80**
Fixes #103 

Updated 3 icons by Telev78 and created a pull request  (chaned toc/authors as well)

### CODE REVIEW

**Comment by Thunderforge** [comment]
Where did the cup for Indy3 come from? It looks pretty low-res, and I don't see it on box art.

I'm not sure I care for the Secret of Monkey Island one omitting "The Secret Of". "Monkey Island" just isn't enough.

"Monkey Island 2: LeChuck's Revenge" is good.

**Comment by GandalfTheWhite80** [comment]
You have to ask @Telev78   - i just made the PR because in my opinion the mew icons are better than the old ones (extra white pixel/hardly readable on dark bakckgrounds)

**Comment by GandalfTheWhite80** [comment]
Made a new monkey version - idea by Telev78 :-) combined just a new guybrush scan and the wikimedia commons monkey island svg. Pls have a look at the discord icons channel.

**Comment by Thunderforge** [comment]
The new icon for _The Secret of Monkey Island_ addresses my concern about omitting "The Secret of", and I appreciate the higher resolution!

image

My only concern now is the Indy 3 logo with the low-res cup that doesn't appear to be from box art or anything.

**Comment by GandalfTheWhite80** [comment]
@Thunderforge  @Telev78

If there are no objections I would commit my proposal of monkey and your (Telev78) version of monkey2. After that I would close this PR (and the issue).

It would be nice @Telev78 if you could submit a new indy3 icon with a better gral image :-)

**Comment by SupSuper** [comment]
I think they're based off the old icons: https://web.archive.org/web/20150607012410/http://www.megamonkey.org/icons/

If so, they should be credited appropriately.

**Comment by GandalfTheWhite80** [comment]
Ok as author to toc.md "Thanius"

**Comment by SupSuper** [comment]
You can credit yourself as well. 😉 We can have multiple authors per icon.

**Comment by Thunderforge** [comment]
@GandalfTheWhite80 I'm happy with a PR for the two Monkey Island logos.

My preference is to remove the Indy 3 logo and submit a better version in a future PR. No cover art is better than a bad cover art in my opinion.

**Comment by GandalfTheWhite80** [comment]
updated monkey1/2 - closing pr.

**Pull request closed without merging**
