### PR TITLE
ICONS: Update icon for kyra-kyra1 (proportions)

### PR DESCRIPTION
**Pull request by beresk137**
Fixed the distortion of the protagonist, added shining effects to the sidekick, restored the sparks and stars from the original art. The resolution now is higher as well.

### CODE REVIEW

**Review by Thunderforge — APPROVED** [review]

**Comment by GandalfTheWhite80** [comment]
I was looking for a good src for the kyra1 icon some time. N1 work!

**Comment by beresk137** [comment]
Well, this is quite awkward: I had prepared an alternate version, but was late to propose it before merge. Sorry for that.

The logo I have used for the first version was taken from the European release of the game, and that red-on-orange part could be uncomfortable to read. So I created another version, from alternatively coloured American release logo. To be fair, those same colours were used in European manual (but not on the box!). I also toned down the glowing effect, sparks, and stars — just a tiny bit, though.

I do apologize for my sluggishness, and so I am not creating another pull request for this icon before being advised to do so. Please have a look at the new version and share your opinion if it is better than the previous one.

kyra-kyra1

**Comment by GandalfTheWhite80** [comment]
I will update the icon with your latest version - advdef is still running (doing some file size reduction). After that I will update the kyra1 icon.

**Comment by GandalfTheWhite80** [comment]
Done: https://github.com/scummvm/scummvm-icons/commit/5cd1b46b6cdeb10be408db4d8b0c49b6a12f738c

**Pull request merged**
