### PR TITLE
ICONS: Add icons for King's Quest I (same icon for agi/sci)

### PR DESCRIPTION
**Pull request by dotdc**
Signed-off-by: David Calvert <davidcalvertfr@gmail.com>

### CODE REVIEW

**Comment by dotdc** [comment]
If the format is good enough, I'll do more missing icons.
If not, let me know what's wrong.

**Comment by dotdc** [comment]
Also added King's Quest II & III

**Comment by SupSuper** [comment]
Looks good, but I don't think the KQ1 icon needs the copyright text.

**Comment by dotdc** [comment]
Sure, just fixed it!

**Comment by SupSuper** [comment]
Thanks!

**Pull request merged**
